### ISSUE TITLE
Keyboard mapping on Mac is wrong.

### ISSUE THREAD

**Issue by ising4jesus** [naTmeg/ScriptedAmigaEmulator#34]
I tried the demo of sysinfo on your website, when I had to type sysinfo to start it.
Instead, what came out was szsinfo!

The Y and Z keys are reversed for a standard Mac keyboard.

**Comment by steffest** [comment]
Just set the correct keyboard in the Amiga preferences? 
Think of it as a virtual machine, with its own localisation settings, independent from the host.

**Comment by naTmeg** [comment]
This is not a bug, but the default keymap for AmigaOS. (english)

To set another keymap, you have to use the command 'setmap', but this command is only supported if it's in the C-directorey, e.g. when using a Workbench-disk.

So for SysInfo, you have to swap z<->y, because setmap is not stored on that disk...
